//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Shoes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticle { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductMeasurementUnit { get; set; }
        public int ProductVendor { get; set; }
        public int ProductCategory { get; set; }
        public byte ProductDiscountAmount { get; set; }
        public byte ProductMaximumDiscount { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductPhoto { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
